### PR TITLE
OPS-2054 Fix chimpd stats.json output

### PR DESCRIPTION
**Pull request by crunis**
This makes the JSON output of /stats.json to return all integers on the values.

Before, "processing" key was returning a string.

### CODE REVIEW

**Comment by markitoxs** [comment]
this looks ok, good catch.

**Comment by markitoxs** [comment]
since @rs-xavier has just merged a new version, please merge master in, and bump your version.

**Comment by crunis** [comment]
done!

**Comment by markitoxs** [comment]
wonderful, thanks!

**Pull request merged**
